Feat/keycloak
tchapgouv/synapse-on-k8s pull request #308
Opened 2024-02-12 17:07 UTC by ad2ien

2024-02-22 10:17 UTC, ad2ien commented
#319 to track to next move about keycloak

2024-02-26 15:05 UTC, heroinedor requested changes

2024-02-26 15:05 UTC, heroinedor commented on ansible/roles/keycloak-operator/tasks/main.yml
don't forget to add a switch "present_or_absent" in order to be able to delete the namespace and its content when destroying the environment

2024-02-26 15:05 UTC, heroinedor commented on ansible/roles/keycloak/templates/keycloak.yml.j2
> +    enabled: false
why is ingress disabled here ?

2024-02-26 15:05 UTC, heroinedor commented on ansible/roles/synapse-extra-config/templates/cm-extraconfig.yml.j2
> +          config:
Is this config correct ?
Shouldn't it be like for prosante connect ?
Something like  :
          config:
            localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
            display_name_template: "{% raw %}{{ user.given_name }} {{ user.family_name }}{% endraw %}"
            email_template: "{% raw %}{{ user.email }}{% endraw %}"

2024-02-26 15:05 UTC, heroinedor commented on ansible/roles/keycloak/tasks/main.yml
> +- name: Wait for the keycloak instance to be up and running
Is there a better way to detect the readiness of keycloak ?

2024-02-26 15:47 UTC, ad2ien commented on ansible/roles/keycloak/templates/keycloak.yml.j2
> +    enabled: false
because we manage the ingress ourself  so we don't need the operator default ingress

2024-02-27 10:25 UTC, heroinedor approved these changes

2024-02-27 10:53 UTC, merged